theme: jekyll-theme-slate
title: Canvas Tool
description: Using python to make Canvas better!
github:
    owner_url: https://www.sjsu.edu/people/ben.reed/
    repository_url: https://github.com/SJSU-CS-systems-group/canvas_tool
